### ISSUE TITLE
can't import misc3d in python

### ISSUE THREAD

**Issue by tonglily** [yuecideng/Misc3D#16]
Hi,i encounter a problem that i can't import misc3d in python.
when i finish your following guide :
1.Build open3d as external library. You can follow the instruction from here [guide](https://github.com/intel-isl/open3d-cmake-find-package). Build pybind11 in your system as well. If you only use C++ API, you can skip this step and just download the pre-built open3d library from [official website](http://www.open3d.org/docs/release/getting_started.html).
2.Git clone and run: mkdir build && cd build. You can use Cmake GUI to configure your build options. Then run cmake --build. --config Release --target INSTALL to install Misc3D.
3.After installation, add this variable: /path/to/installation/misc3d/lib/python to your system environment variable Path to make sure you can import misc3d in python.

i don't know why i still can't import misc3d,hope your rely.

**Comment by yuecideng** [comment]
Could you find `Open3D.dll` in `../misc3d/bin/` folder? If not, please try copying this file to here and check again.

**Comment by tonglily** [comment]
i can't find open3d.dll in my computer,where to find it?

**Comment by yuecideng** [comment]
You should build Open3D with cmake param `-DBUILD_SHARED_LIBS=ON` to generate `*.dll` lib file. For static library mode, I have not test yet.

**Comment by tonglily** [comment]
thanks your rely!i will try later.

**Comment by tonglily** [comment]
it means I  pre-build Open3D c++ Release and install python package(open3d) via pip  in my python environment. and then I can install misc3d via the order "pip install misc3d"?

**Comment by yuecideng** [comment]
Close due to lack of discussion
