### ISSUE TITLE
how can i tune the parameters that i can get a better result

### ISSUE THREAD

**Issue by tonglily** [yuecideng/Misc3D#17]
hi,when i use ppf_3d_icp,i find the result is not so well.
i want to know what parameter i can tune
i only tune the rel_sample_dist and score_thresh,so that more points can be counted in estimator.
what else parameters can i tune,hope your reply.

**Comment by yuecideng** [comment]
What kind of model and scene point cloud you try to estimate? The results I submit in BOP challenge use object detection to crop object instance from origin input and only use the cropped object point cloud for pose estimation.

Sorry for lack of API document currently, but you can find all the params in `python/py_pose_estimation.cpp` related to PPF estimator. The typical param that has greatest impact of the performance is`rel_sample_dist`.

**Comment by tonglily** [comment]
i did use the cropped object point cloud,i don't know whether if the quality of my object point cloud is not good .
the result is  in following images: the first image is the crop object,the second image is the ppf result.
![微信图片_20220410210034](https://user-images.githubusercontent.com/89839634/162619709-107cface-6374-4017-8fed-c6732a628f48.png)
![微信图片_20220410210049](https://user-images.githubusercontent.com/89839634/162619715-3f3aa6b9-2bb7-42b4-a1bd-5190e98efd2a.png)

**Comment by yuecideng** [comment]
The PPF estimator is not suitable for object with flat shape, but maybe you can try to set `VotingMode` to `EdgePoints` and see whether it would be better.

**Comment by yuecideng** [comment]
Close due to lack of discussion
