### ISSUE TITLE
关于编译misc3d项目

### ISSUE THREAD

**Issue by mougg-78** [yuecideng/Misc3D#2]
1.open3d == 0.14.1是什么意思呢，是用open3d 为0.14.1的包去编译吗？
2.Build open3d as external library. 这个的意思是先按照https://github.com/isl-org/open3d-cmake-find-package的指示去编译open3d包吗，能不能说明下具体编译步骤，因为编译open3d按照https://github.com/isl-org/open3d-cmake-find-package的方法很难编译成功，因为需要一些很难解决的依赖问题。
谢谢你

**Comment by yuecideng** [comment]
1. 意思是把源代码切换到版本0.14.1, 可以在`Open3D`根目录下运行`git checkout v0.14.1`完成切换
2. 先运行`util/install_deps_ubuntu.sh` 下载必要的软件依赖，然后运行
```
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_PYTHON_MODULE=ON \
    -DGLIBCXX_USE_CXX11_ABI=ON \
    ..
make install -j4
```

**Comment by sunhan1997** [comment]
您好，我按照你上面的安装open3D之后，编译misc3D出现下面报错，请问这是open3d没有编译好吗？
![Screenshot from 2022-09-29 18-46-49](https://user-images.githubusercontent.com/53546795/193012118-dd6a98ce-4d2c-4136-9282-91cecfe6ce45.png)

**Comment by yuecideng** [comment]
需要`cmake .. -DOpen3D_DIR=/path/to/open3d_install`让cmake找到open3d的安装路径

**Comment by Jingranxia** [comment]
你好，后来编译成功了吗
