### ISSUE TITLE
build error: undefined reference to `open3d::core::Tensor::~Tensor()'

### ISSUE THREAD

**Issue by SubChange** [yuecideng/Misc3D#21]
I'm very interesting in your work. I have spent a lot of time to build the codes on ununtu20.04,  but it still have problems. The environment I used is as the follow:

- Ubuntu20.04
- Open3D v0.15.1
- python=3.7
- pybind=2.10.0dev1

I have build the Open3D from source successfully. Then, I have install Misc3D according to your tutorial, the commands are as follows

```text
git clone https://github.com/yuecideng/Misc3D.git

cd Misc3D

mkdir build
mkdir misc3d_install
cd build

cmake -DCMAKE_PREFIX_PATH=/home/subchange/dev_build/Open3D/install -DCMAKE_INSTALL_PREFIX=../misc3d_install ..

```
Note that the path `/home/subchange/dev_build/Open3D/install ` is the path where I have install Open3D

Please see the errors in the follow

![image-20220504204106460](https://user-images.githubusercontent.com/28522692/166687426-1b032ae2-2616-4248-b13b-df3482425910.png)

![image-20220504205605428](https://user-images.githubusercontent.com/28522692/166687469-4d8179c8-4130-4339-bfef-c5333f774d8a.png)

![image-20220504205630117](https://user-images.githubusercontent.com/28522692/166687524-4dbb5335-8383-4397-9c18-18a7394d6396.png)

![image-20220504205657777](https://user-images.githubusercontent.com/28522692/166687610-9194a078-daef-4013-89f4-092f437e0784.png)

![image-20220504205722222](https://user-images.githubusercontent.com/28522692/166687650-712cd6c7-6444-42b5-b973-df91e0247773.png)

![image-20220504205305559](https://user-images.githubusercontent.com/28522692/166687669-56ff6f2d-2061-4fb4-b56a-70f32e4280b2.png)

I do not good at c++ language. Cloud you please give me some help to build the project from source? Thank you very much.

**Comment by yuecideng** [comment]
Hi, could you show me your cmake configuration for `open3d`？ Please check that `-DGLIBCXX_USE_CXX11_ABI=ON` is set when you build `open3d` from source.

**Comment by SubChange** [comment]
I have build Open3D using the follow commands:

```text

git clone --recursive https://github.com/intel-isl/Open3D
git checkout v0.15.1

util/install_deps_ubuntu.sh -y

mkdir build
mkdir install
cd build

conda activate py37
which python

cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug .. 


make -j4
make install -j4
make pip-package

```
It has generate the *.whl file (build/lib/python_package/pip_package/open3d-0.13.0+c3f9de224-cp37-cp37m-manylinux_2_31_x86_64.whl)

The result are as follows:

![image-20220504214200312](https://user-images.githubusercontent.com/28522692/166694447-a6681877-4e14-4b9b-8741-8347ace7d673.png)

![image-20220504214217326](https://user-images.githubusercontent.com/28522692/166694475-be9c621f-bdba-4865-a896-4e5f99ed5b97.png)

**Comment by yuecideng** [comment]
Maybe try to set `-DDBUILD_SHARED_LIBS=ON`  to build shared library for `open3d`, since I did not try static library under linux platform...

I will try your configuration mentioned above to see how to solve this probelm. But it may take some time.

**Comment by SubChange** [comment]
hello, thank you for your help. I have rebuild the Open3D with `CMAKE_BUILD_TYPE=Release`, `-DBUILD_SHARED_LIBS=ON ` and `-DGLIBCXX_USE_CXX11_ABI=ON`. Open3D was successfully build, but there are some warnings during building as the follow. However, I have not encountered these warnings with  `CMAKE_BUILD_TYPE=Debug`

![image-20220504234714589](https://user-images.githubusercontent.com/28522692/166853078-06758733-0103-48b6-a1e1-28fa85d3eb39.png)

Then, when I build MIsc3D, no errors occurred, again only some warnings

![image-20220505000600999](https://user-images.githubusercontent.com/28522692/166853207-9643051b-8565-4e71-8ab5-d5c7c4e89397.png)

After I set path in `~/.bashrc`, I successfully ran the following code.

```python
import numpy as np
import time
from random import random
import open3d as o3d
import misc3d as m3d

pcd = o3d.io.read_point_cloud('../data/segmentation/test.ply')

t0 = time.time()
results = m3d.segmentation.segment_plane_iterative(pcd, 0.01, 100, 0.1)
print('Segmentation time: %.3f' % (time.time() - t0))

show = []
for cluster in results:
    w, c = cluster
    c.paint_uniform_color(np.array([random(), random(), random()]))
    show.append(c)

o3d.visualization.draw_geometries(show, 'Iterative Plane Segmentation')
```
I don't know if there is anything wrong with those warnings, have you encountered them during building from source?

In sum, though some warnings occurred, It seems that it works. It works anyway. I have listed my commands as follows:

**Open3D**
```text
git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D

git tag
git checkout v0.15.1

git submodule update --init --recursive

util/install_deps_ubuntu.sh -y

mkdir build
mkdir open3d_install
cd build

conda activate py37
which python

cmake -DCMAKE_INSTALL_PREFIX=../open3d_install -DCMAKE_BUILD_TYPE=Debug .. #Failed

cmake -DBUILD_SHARED_LIBS=ON -DGLIBCXX_USE_CXX11_ABI=ON -DCMAKE_INSTALL_PREFIX=../open3d_install -DCMAKE_BUILD_TYPE=Release ..

make -j4
make install -j4
make pip-package

```


**Misc3D**

```text
git clone https://github.com/yuecideng/Misc3D.git

cd Misc3D

mkdir build
   
mkdir misc3d_install
    
cd build

conda activate py37
    
cmake -DCMAKE_PREFIX_PATH=/home/subchange/dev_build/Open3D/open3d_install -DCMAKE_INSTALL_PREFIX=../misc3d_install ..
    
make install -j
```

It should be mentioned that I have make some modifications to the `Misc3D/CMakeLists.txt` file in line 72 to help it found Open3D library.

```text
#find_package(Open3D REQUIRED NO_DEFAULT_PATH)
find_package(Open3D REQUIRED)
message(STATUS "Open3D_DIR = ${Open3D_DIR}")
message(STATUS "Open3D_INCLUDE_DIRS = ${Open3D_INCLUDE_DIRS}")
message(STATUS "Open3D_LIBS = ${Open3D_LIBS}")
```

**Comment by yuecideng** [comment]
Glad to hear that. 

The warning messages can be mostly igored. Don't worry about them.  You can set `-DOpen3D_DIR=/path/to/install/open3d` to cmake configure without change the original `CMakeLists.txt`.

**Comment by SubChange** [comment]
> Glad to hear that.
> 
> The warning messages can be mostly igored. Don't worry about them. You can set `-DOpen3D_DIR=/path/to/install/open3d` to cmake configure without change the original `CMakeLists.txt`.

I have tried this setting `-DOpen3D_DIR=/path/to/install/open3d`, however, it didn't work. I delete `NO_DEFAULT_PATH` in the sentence `find_package(Open3D REQUIRED NO_DEFAULT_PATH)` and set `-DCMAKE_PREFIX_PATH=/home/subchange/dev_build/Open3D/open3d_install`, then, it works. Anyway, it works now. thank you very much.
