### ISSUE TITLE
Questions about pose_estimation

### ISSUE THREAD

**Issue by doublexxking** [yuecideng/Misc3D#24]
Thanks for your great work firstly.
However, I have an issue about pose_estimation section.
Does pose_estimation can only detect one side of object?

My object is irregular industrial sheetmetal, as the object in scene is forward,  pose_estimation can detect very well.
But if the irregular industrial sheetmetal is inverted,  pose_estimation must be failed, the results of the pose form pose_estimation is always forward direction. 
I know there is config.training_param_.invert_model_normal, if I set config.training_param_.invert_model_normal is true,  the pose form pose_estimation is always backward direction that it cannot detect the forward direction.

My question is if there some method that I can detect the object whatever the direction is forward or backward ?

**Comment by yuecideng** [comment]
Hi, thanks for your interest.

I think it maybe due to the shape of your industrial model (eg. the surface are similar for both forward and backward)。
A tricky method you can used is that, you can train two detectors with invert_model_normal set to True and False. Than apply detection to your scene data, selecting the result with higher `score` of output result. If the `score` is not distinguish enough, you can use the fitness value from `ICP`。

**Comment by doublexxking** [comment]
I already your method, it could be worked, but it cost much more time.
What confused me is that the original model normals are both side, for example, the forward side is upward and the backward side is downward, but pose_estimation could only choose pose from one side?

**Comment by yuecideng** [comment]
The model normals are pre-computed by your self or computed inside the training stage? Could you show me your model normals if possible?

**Comment by doublexxking** [comment]
I pre computed by myself and donot use your view-point method (although I tried your method, it also not work).

I put the model in baidu disk. It is thankful that you could check.

https://pan.baidu.com/s/1xlyr0Zvsmi3ZCk9VEGaUMA?pwd=f2rv
password: f2rv

**Comment by yuecideng** [comment]
Thanks for your sharing. I think your model and normals are fine. Maybe you could share a scene data so I can check the algorihm by by myself.

**Comment by doublexxking** [comment]
Here it is
https://pan.baidu.com/s/17odm4u5p6ycZojkfmwqBhg?pwd=3w5p 
password: 3w5p

**Comment by yuecideng** [comment]
Thanks, I will update if I have any progress about it.
