### ISSUE TITLE
ImportError: libmisc3d.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jiaming3** [yuecideng/Misc3D#30]
Hi @yuecideng , I installed the Misc3D lib and successfully ran through few example python scripts in terminal. However, when I run script in pycharm then it occur import error and the terminal become like this as well.  How can I solve this problem?

**Comment by yuecideng** [comment]
You should check that the python versions used in your terminal and pycharm are equal or not. Keep them with the same python interpreter should work.

**Comment by jiaming3** [comment]
It seems like the gedit .bashrc method to export the misc3d path is not stable in my conda virtual environment. I rebuild the Misc3D and it work, but I close the terminal and it occur the same error even through I gedit .bashrc again.
