### ISSUE TITLE
How do I compile Misc3D OFFLINE?

### ISSUE THREAD

**Issue by Tianpapa** [yuecideng/Misc3D#4]
It's been too many trouble to compile Open3D offline, so I give up. Instead, using the [x86_64 (pre CXX11 ABI) with CUDA 11.x](https://storage.googleapis.com/open3d-releases-master/devel/open3d-devel-linux-x86_64-pre-cxx11-abi-cuda-0.15.2+b15f8af.tar.xz) Package. However, encounter this error

...
/usr/bin/ld: /data1/install/Open3D_install/lib/libOpen3D.so: undefined reference to `std::__1::ios_base::__set_badbit_and_consider_rethrow()'
/usr/bin/ld: /data1/install/Open3D_install/lib/libOpen3D.so: undefined reference to `typeinfo for std::__1::basic_istream<char, std::__1::char_traits<char> >'
/usr/bin/ld: /data1/install/Open3D_install/lib/libOpen3D.so: undefined reference to `std::__1::random_device::operator()()'
...

Any advice maybe?

**Comment by yuecideng** [comment]
Try `x86_64 (CXX11 ABI)` or `x86_64 (CXX11 ABI) with CUDA 11.x`

**Comment by Tianpapa** [comment]
> Try `x86_64 (CXX11 ABI)` or `x86_64 (CXX11 ABI) with CUDA 11.x`

Still. I tried. However the same output when I run `make install -j`
![屏幕截图(225)](https://user-images.githubusercontent.com/36984108/157359203-d4c80b21-195b-41d7-9ad3-884564913948.png)

**Comment by yuecideng** [comment]
Two things should be confirmed: 
1. You have run `./util/install_deps_ubuntu.sh` before you compile misc3d.
2. Please go to the location of `libOpen3D.so` and run `ldd libOpen3D.so` to see whether some linking libs are missed.

**Comment by Tianpapa** [comment]
> Two things should be confirmed:
> 
> 1. You have run `./util/install_deps_ubuntu.sh` before you compile misc3d.
> 2. Please go to the location of `libOpen3D.so` and run `ldd libOpen3D.so` to see whether some linking libs are missed.

THANKS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
After runing `./util/install_deps_ubuntu.sh`
'libc++.so.1 => not found' been fixed!
It's turned out [x86_64 (pre CXX11 ABI) with CUDA 11.x](https://storage.googleapis.com/open3d-releases-master/devel/open3d-devel-linux-x86_64-pre-cxx11-abi-cuda-0.15.2+b15f8af.tar.xz) works just as well.
Finally, successfully compiled.
Can't be more appreciative!

However, 
![屏幕截图(228)](https://user-images.githubusercontent.com/36984108/157369824-33960325-90e9-4de9-9ba9-06033834c1f3.png)

**Comment by yuecideng** [comment]
The success of compilation just make sure you can use c++ api. If you want to use python api, currently you should compile `open3d` from source and install python binding aswell, see [this](http://www.open3d.org/docs/release/compilation.html).

The reason is that both `open3d` and `misc3d` use `pybind11` to provide python wrapper.  The `open3d` python package you used maybe install by `pip3 install open3d`, which contains the pre-build cpp static library of open3d, and in `misc3d` pybind cannot find that.

My suggestion is that i you want to use both cpp&python api, just build `open3d` from souce:
```
util/install_deps_ubuntu.sh
mkdir build && cd build
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_GUI=ON \
    -DBUILD_PYTHON_MODULE=ON \
    -DGLIBCXX_USE_CXX11_ABI=ON \
    ..
sudo make install -j
# install python binding
sudo make python-package
cd lib && sudo pip3 install python_package
```

**Comment by Tianpapa** [comment]
Thanks, man.
Though build `Open3D` from souce have been a tough challenge for me in consideration of the remote server's in a Internal Network, you firmed my pace. After download 29 packages from github with my bare hand and put them in place in Open3D/3rdparty_downloads, ffffffffinally, it worked...till encountering another error

`root@train-regis-0307-0:/data1/install/Open3D/build/lib/python_package# pip3 install .
Looking in indexes: http://af.hikvision.com.cn/artifactory/api/pypi/pypi/simple
Processing /data1/install/Open3D/build/lib/python_package
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.18.0 in /usr/local/miniconda3/lib/python3.8/site-packages (from open3d==0.15.2) (1.21.4)
Requirement already satisfied: wheel>=0.36.0 in /usr/local/miniconda3/lib/python3.8/site-packages (from open3d==0.15.2) (0.37.0)
Requirement already satisfied: setuptools>=40.8.0 in /usr/local/miniconda3/lib/python3.8/site-packages (from open3d==0.15.2) (60.8.2)
Building wheels for collected packages: open3d
  Building wheel for open3d (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for open3d (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [321 lines of output]
      running bdist_wheel
      running build
      running build_py
      running egg_info
      writing open3d.egg-info/PKG-INFO
      writing dependency_links to open3d.egg-info/dependency_links.txt
      writing entry points to open3d.egg-info/entry_points.txt
      writing requirements to open3d.egg-info/requires.txt

      ……

      copying build/lib/open3d/_build_config.py -> build/bdist.linux-x86_64/wheel/open3d
      running install_egg_info
      running install_scripts
      Traceback (most recent call last):
        File "/usr/local/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-99vuc1fd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-99vuc1fd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-99vuc1fd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 196, in <module>
          setup(**setup_args)
        File "/tmp/pip-build-env-99vuc1fd/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-99vuc1fd/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-99vuc1fd/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-99vuc1fd/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-99vuc1fd/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-99vuc1fd/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 351, in run
          self.egg2dist(self.egginfo_dir, distinfo_dir)
        File "/tmp/pip-build-env-99vuc1fd/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 471, in egg2dist
          pkg_info = pkginfo_to_metadata(egginfo_path, pkginfo_path)
        File "/tmp/pip-build-env-99vuc1fd/overlay/lib/python3.8/site-packages/wheel/metadata.py", line 70, in pkginfo_to_metadata
          pkg_info.replace_header('Metadata-Version', '2.1')
        File "/usr/local/miniconda3/lib/python3.8/email/message.py", line 558, in replace_header
          raise KeyError(_name)
      KeyError: 'metadata-version'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for open3d
Failed to build open3d
ERROR: Could not build wheels for open3d, which is required to install pyproject.toml-based projects
`
Your help gives me a more comprehensive understanding of CMake
Appreciate your kindness and patience.

**Comment by yuecideng** [comment]
Have you try `sudo pip3 install .`?

**Comment by Tianpapa** [comment]
Finally
![image](https://user-images.githubusercontent.com/36984108/157433302-ae4fbf7a-3b7f-4ba9-a7ff-9e50c30f213f.png)
Thanks for your help!!!!!!!!!!

**Comment by yuecideng** [comment]
Glad to see that! Feel free to report issues if you have any questions or problems about Misc3D.

不客气 😁
