### ISSUE TITLE
Question about BOP Submission: PPF_3D_ICP

### ISSUE THREAD

**Issue by Tianpapa** [yuecideng/Misc3D#6]
While using PPF in 6D Object Pose Estimation, the scene PointCloud you used is directly created from original color and depth, or after RoI crop using bbox/mask?

**Comment by yuecideng** [comment]
```python
# crop roi from point clouds using given bbox of image
scene_crop = m3d.preprocessing.crop_roi_pointcloud(
    scene, (222, 296, 41 + 222, 44 + 296), (640, 480))

# mathch scene points
ret, results = ppf.estimate(scene_crop)
```
As show above, pointcloud crop by bbox is used, which makes it more rubust and fast for estimation

**Comment by Tianpapa** [comment]
Roger that. Thanks.
