### ISSUE TITLE
How should 'score_thresh' be set to make sure ret is True?

### ISSUE THREAD

**Issue by Tianpapa** [yuecideng/Misc3D#7]
In examples/python/test_ppf_estimator.py
```
# init ppf config
config = m3d.pose_estimation.PPFEstimatorConfig()
# init training param
config.training_param.rel_sample_dist = 0.04
config.score_thresh = 0.05
config.refine_param.method = m3d.pose_estimation.PPFEstimatorConfig.PointToPlane
```
What does `rel_sample_dist` mean?

When I set `score_thresh` to 0, I get "No match" as usual, I know 0 means Default, which is 0.05.
However, when I set `score_thresh` to 0.001, in rare cases, I still got "No match". 
I assure `config.score_thresh = 1e-10` may work when at least one result is needed. 
Maybe there is a offical way to do it?

**Comment by yuecideng** [comment]
1. `rel_sample_dist` is a relative factor to control the sample distane for point clouds. the sample dist is equal to `rel_sample_dist * model_diameter` . 
2. Did you see the printed infomation in console? `score_thresh` is use to supress the estimated pose, if there is no pose estimated, whatever you set this value, there is always no result.

**Comment by Tianpapa** [comment]
Thanks for your answer!
