### ISSUE TITLE
How did you manage to get a bop19_average_recall of 0.411 on YCB-V dataset?

### ISSUE THREAD

**Issue by Tianpapa** [yuecideng/Misc3D#8]
How did you manage to get a bop19_average_recall of 0.411 on YCB-V dataset?
I tried gt_mask and ppf+icp on ycbv/test_targets_bop19, however, only get a score of 0.3094.
Once before I tried ppf on lm dataset, AR is 0.817, as good as yours.
I wanna know what could be wrong on ycbv, how'd you manage to fulfill sparse icp and dense icp?
Maybe you could open source your BOP submit pipeline?

**Comment by yuecideng** [comment]
I used the following configuration for PPF:
```python
    config.training_param.rel_sample_dist = 0.03
    config.voting_param.faster_mode = False
    config.score_thresh = 0.01
    config.refine_param.method = m3d.pose_estimation.PPFEstimatorConfig.PointToPoint
    config.ref_param.ratio = 1.0
```
and 0.01 for `ICP` max distance.
Just for your reference, the code of the pipeline is still under development, maybe I will open source in the future.

**Comment by Tianpapa** [comment]
Thank you for answering!
