### ISSUE TITLE
C++ installation has error loading library

### ISSUE THREAD

**Issue by Xieyuan0018** [yuecideng/Misc3D#9]
Hi, I was having a hard time installing the python version but managed to install the c++ version. 

However, when I tried to run the examples, there was an error saying "./ransac_and_boundary: error while loading shared libraries: libmisc3d.so: cannot open shared object file: No such file or directory" 

I've checked the lib and it was in the lib directory. How should I load it?

Any suggestion to solve the problem would be very appreciated. Thanks!

**Comment by yuecideng** [comment]
Did you add `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:</path/to/installation>/misc3d/lib"` in your `~/.bashrc` file? Don't forget to save it by `souces ~/.bashrc`.
By the way, what problems you met when you installed python binding?

**Comment by Xieyuan0018** [comment]
> Did you add `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:</path/to/installation>/misc3d/lib"` in your `~/.bashrc` file? Don't forget to save it by `sources ~/.bashrc`. By the way, what problems you met when you installed python binding?

Hi, I saw in the guide you mentioned that this step is not needed if not building python binding so I didn't do that. Anyway I tried it just now and the library was loaded, but I got another error:

`$ ./ransac_and_boundary
[Misc3D INFO] Find best model with 24.2282% inliers and run 696 iterations
Time cost for fitting: 0.0422513
[Misc3D INFO] Found 1136 boundary points from 10940 input points.
Time cost for boundary detection: 0.0473595
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
Segmentation fault (core dumped)`

For the python binding, I followed all the steps in the guide and managed to build it, but there were errors when I tried to use it. For example: 
`>>> normal = m3d.common.estimate_normals(pcd, (640, 480), 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: [Misc3D Error] (void misc3d::common::EstimateNormalsFromMap(const PointCloudPtr&, std::tuple<int, int>, int, const std::array<double, 3>&)) /home/user/Misc3D/src/normal_estimation.cpp:191: The point cloud size is not equal to given point map size.

>>> w, indices = m3d.common.fit_cylinder(pcd, 0.01, 100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: std::bad_alloc
>>> indices = m3d.preprocessing.farthest_point_sampling(pcd, 1000)
[Misc3D INFO] This method has been added to Open3D official branch and hence it will be deprecated in the future.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: [Misc3D Error] (std::vector<long unsigned int> misc3d::preprocessing::FarthestPointSampling(const open3d::geometry::PointCloud&, int)) /home/user/Misc3D/src/filter.cpp:28: Illegal number of samples: 1000, must <= point size: 0`

**Comment by yuecideng** [comment]
1. Did you run your program in server? The error message shows the absensce of `GLFW`. 
2. I think you try illegal input args for the functions. For example, you should know that for normals estimation from `PointMap`, the size of `pcd` must be equal to `640 * 480`, so please check that. 

The python API examples in the guide is kind of pseudo code, I think you should create a real `pcd` instance from your data before you run the example.

**Comment by Xieyuan0018** [comment]
> 1. Did you run your program in server? The error message shows the absensce of `GLFW`.
> 2. I think you try illegal input args for the functions. For example, you should know that for normals estimation from `PointMap`, the size of `pcd` must be equal to `640 * 480`, so please check that.
> 
> The python API examples in the guide is kind of pseudo code, I think you should create a real `pcd` instance from your data before you run the example.

1. Thanks for the hint. I was running from remote. Tried again on the workstation itself and it worked!
2. Yeah I know that the error for estimate_normals may be due to function parameters. How about the other two function calls? common.fit_cylinder and preprocessing.farthest_point_sampling. I did load the point cloud using open3d.io.read_point_cloud function.

**Comment by yuecideng** [comment]
For ` m3d.common.fit_cylinder(pcd, 0.01, 100)`, I will try some test data, or maybe you can provide your data for me to reproduce the error?
For the second, the error says `Illegal number of samples: 1000, must <= point size: 0`, which means your `pcd` has 0 points.

**Comment by Xieyuan0018** [comment]
> m3d.preprocessing.farthest_point_sampling(pcd, 1000)

I double checked the point size, it was not empty:
`>>> data = pcd.points
>>> import numpy as np
>>> datanp =np.asarray(data)
>>> datanp.shape
(88783, 3)`

Here is the link to the data: [https://drive.google.com/file/d/1Avou7BiZ1B2yrG82C4YEP_fBiXcnAw-t/view?usp=sharing](url) Thanks so much for the help!

**Comment by yuecideng** [comment]
Hi, 
I have tried your data, the `farthest_point_sampling` can run properly like this:
```python
data = np.loadtxt('../../../../Downloads/lab_cylinder1.txt')
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(data[:, :3])

indices = m3d.preprocessing.farthest_point_sampling(pcd, 1000)
sample = pcd.select_by_index(indices)
o3d.visualization.draw_geometries([sample])
```
<img width="841" alt="image" src="https://user-images.githubusercontent.com/42235877/159834977-69af0a17-eba1-487b-b371-9715f5cda695.png">

As for `fit_cylinder`, it has bug and I am trying to fix it.

**Comment by Xieyuan0018** [comment]
For `farthest_point_sampling`,  I tried to load data in your way but still got the same error `Illegal number of samples: 1000, must <= point size: 0`.
And same "MemoryError: std::bad_alloc" error for `m3d.common.fit_cylinder` after adding `estimate_normals()`

I think I'll just use the C++ API for now. Thanks so much!

**Comment by yuecideng** [comment]
Keep this issue open if someone meet the same problems.
